"""initial_schema

Revision ID: aa70f58fa461
Revises: 
Create Date: 2026-08-11 12:42:09.725437

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = "aa70f58fa461"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "targets",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("provider_type", sa.String(length=50), nullable=False),
        sa.Column("endpoint_url", sa.String(length=512), nullable=True),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "experiments",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("attack_budget", sa.Integer(), nullable=False),
        sa.Column("exploration_ratio", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiments_status"), "experiments", ["status"], unique=False
    )
    op.create_table(
        "agent_runs",
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("agent_role", sa.String(length=50), nullable=False),
        sa.Column("input_summary", sa.Text(), nullable=True),
        sa.Column("output_summary", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"], ["experiments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_runs_experiment_id"),
        "agent_runs",
        ["experiment_id"],
        unique=False,
    )
    op.create_table(
        "analytics_reports",
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("summary_markdown", sa.Text(), nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"], ["experiments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analytics_reports_experiment_id"),
        "analytics_reports",
        ["experiment_id"],
        unique=False,
    )
    op.create_table(
        "attacks",
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("strategy_name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("prompt_text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"], ["experiments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_attacks_category"), "attacks", ["category"], unique=False)
    op.create_index(
        op.f("ix_attacks_experiment_id"), "attacks", ["experiment_id"], unique=False
    )
    op.create_table(
        "attack_mutations",
        sa.Column("parent_attack_id", sa.UUID(), nullable=False),
        sa.Column("child_attack_id", sa.UUID(), nullable=False),
        sa.Column("mutation_type", sa.String(length=100), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_attack_id"], ["attacks.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_attack_id"], ["attacks.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attack_mutations_child_attack_id"),
        "attack_mutations",
        ["child_attack_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attack_mutations_parent_attack_id"),
        "attack_mutations",
        ["parent_attack_id"],
        unique=False,
    )
    op.create_table(
        "attack_results",
        sa.Column("attack_id", sa.UUID(), nullable=False),
        sa.Column("target_response", sa.Text(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("token_usage_json", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["attack_id"], ["attacks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attack_results_attack_id"),
        "attack_results",
        ["attack_id"],
        unique=False,
    )
    op.create_table(
        "model_calls",
        sa.Column("agent_run_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"], ["agent_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_model_calls_agent_run_id"),
        "model_calls",
        ["agent_run_id"],
        unique=False,
    )
    op.create_table(
        "vulnerabilities",
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("attack_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("verified_status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["attack_id"], ["attacks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["experiment_id"], ["experiments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vulnerabilities_attack_id"),
        "vulnerabilities",
        ["attack_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vulnerabilities_category"),
        "vulnerabilities",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vulnerabilities_experiment_id"),
        "vulnerabilities",
        ["experiment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vulnerabilities_severity"),
        "vulnerabilities",
        ["severity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vulnerabilities_verified_status"),
        "vulnerabilities",
        ["verified_status"],
        unique=False,
    )
    op.create_table(
        "defenses",
        sa.Column("vulnerability_id", sa.UUID(), nullable=False),
        sa.Column("strategy_name", sa.String(length=100), nullable=False),
        sa.Column("defense_config_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vulnerability_id"], ["vulnerabilities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_defenses_vulnerability_id"),
        "defenses",
        ["vulnerability_id"],
        unique=False,
    )
    op.create_table(
        "regression_tests",
        sa.Column("vulnerability_id", sa.UUID(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["vulnerability_id"], ["vulnerabilities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_regression_tests_target_id"),
        "regression_tests",
        ["target_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_regression_tests_vulnerability_id"),
        "regression_tests",
        ["vulnerability_id"],
        unique=False,
    )
    op.create_table(
        "defense_tests",
        sa.Column("defense_id", sa.UUID(), nullable=False),
        sa.Column("attack_id", sa.UUID(), nullable=False),
        sa.Column("test_type", sa.String(length=50), nullable=False),
        sa.Column("blocked", sa.Boolean(), nullable=False),
        sa.Column("false_positive", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["attack_id"], ["attacks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["defense_id"], ["defenses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_defense_tests_attack_id"), "defense_tests", ["attack_id"], unique=False
    )
    op.create_index(
        op.f("ix_defense_tests_defense_id"),
        "defense_tests",
        ["defense_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_defense_tests_defense_id"), table_name="defense_tests")
    op.drop_index(op.f("ix_defense_tests_attack_id"), table_name="defense_tests")
    op.drop_table("defense_tests")
    op.drop_index(
        op.f("ix_regression_tests_vulnerability_id"), table_name="regression_tests"
    )
    op.drop_index(op.f("ix_regression_tests_target_id"), table_name="regression_tests")
    op.drop_table("regression_tests")
    op.drop_index(op.f("ix_defenses_vulnerability_id"), table_name="defenses")
    op.drop_table("defenses")
    op.drop_index(
        op.f("ix_vulnerabilities_verified_status"), table_name="vulnerabilities"
    )
    op.drop_index(op.f("ix_vulnerabilities_severity"), table_name="vulnerabilities")
    op.drop_index(
        op.f("ix_vulnerabilities_experiment_id"), table_name="vulnerabilities"
    )
    op.drop_index(op.f("ix_vulnerabilities_category"), table_name="vulnerabilities")
    op.drop_index(op.f("ix_vulnerabilities_attack_id"), table_name="vulnerabilities")
    op.drop_table("vulnerabilities")
    op.drop_index(op.f("ix_model_calls_agent_run_id"), table_name="model_calls")
    op.drop_table("model_calls")
    op.drop_index(op.f("ix_attack_results_attack_id"), table_name="attack_results")
    op.drop_table("attack_results")
    op.drop_index(
        op.f("ix_attack_mutations_parent_attack_id"), table_name="attack_mutations"
    )
    op.drop_index(
        op.f("ix_attack_mutations_child_attack_id"), table_name="attack_mutations"
    )
    op.drop_table("attack_mutations")
    op.drop_index(op.f("ix_attacks_experiment_id"), table_name="attacks")
    op.drop_index(op.f("ix_attacks_category"), table_name="attacks")
    op.drop_table("attacks")
    op.drop_index(
        op.f("ix_analytics_reports_experiment_id"), table_name="analytics_reports"
    )
    op.drop_table("analytics_reports")
    op.drop_index(op.f("ix_agent_runs_experiment_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index(op.f("ix_experiments_status"), table_name="experiments")
    op.drop_table("experiments")
    op.drop_table("targets")
    op.drop_table("projects")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
