"""initial_schema

Revision ID: aa70f58fa461
Revises:
Create Date: 2026-08-11 12:42:09.725437

Rewritten during Phase 1 to be the single source of truth for the ORM schema:

  * `agent_runs` and `attack_mutations` now match the ORM models exactly
    (prior revision had columns no model uses).
  * Orphan tables without ORM models were removed:
    `analytics_reports`, `model_calls`, `defenses`, `regression_tests`,
    `defense_tests`.
  * Added indexes used by ownership/aggregation queries
    (`projects.owner_id`, `targets.project_id`, `experiments.project_id`).
  * pgvector ``CREATE EXTENSION`` handling moved to ``alembic/env.py`` where it
    is guarded to run only on PostgreSQL.

Requires pgvector to be installed on the target PostgreSQL server
(use the ``ankane/pgvector`` / ``pgvector/pgvector`` Docker image in prod).
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = "aa70f58fa461"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_owner_id"), "projects", ["owner_id"], unique=False)

    op.create_table(
        "targets",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("provider_type", sa.String(length=50), nullable=False),
        sa.Column("endpoint_url", sa.String(length=512), nullable=True),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_targets_project_id"), "targets", ["project_id"], unique=False)

    op.create_table(
        "experiments",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("attack_budget", sa.Integer(), nullable=False),
        sa.Column("exploration_ratio", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_experiments_status"), "experiments", ["status"], unique=False)
    op.create_index(
        op.f("ix_experiments_project_id"), "experiments", ["project_id"], unique=False
    )

    op.create_table(
        "attacks",
        sa.Column("experiment_id", sa.Uuid(), nullable=False),
        sa.Column("strategy_name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("prompt_text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_attacks_category"), "attacks", ["category"], unique=False)
    op.create_index(
        op.f("ix_attacks_experiment_id"), "attacks", ["experiment_id"], unique=False
    )

    op.create_table(
        "attack_results",
        sa.Column("attack_id", sa.Uuid(), nullable=False),
        sa.Column("target_response", sa.Text(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("token_usage_json", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["attack_id"], ["attacks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attack_results_attack_id"),
        "attack_results",
        ["attack_id"],
        unique=False,
    )

    op.create_table(
        "vulnerabilities",
        sa.Column("experiment_id", sa.Uuid(), nullable=False),
        sa.Column("attack_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("verified_status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["attack_id"], ["attacks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["experiment_id"], ["experiments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vulnerabilities_attack_id"), "vulnerabilities", ["attack_id"], unique=False
    )
    op.create_index(
        op.f("ix_vulnerabilities_category"), "vulnerabilities", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_vulnerabilities_experiment_id"),
        "vulnerabilities",
        ["experiment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vulnerabilities_severity"), "vulnerabilities", ["severity"], unique=False
    )
    op.create_index(
        op.f("ix_vulnerabilities_verified_status"),
        "vulnerabilities",
        ["verified_status"],
        unique=False,
    )

    op.create_table(
        "agent_runs",
        sa.Column("experiment_id", sa.Uuid(), nullable=False),
        sa.Column("agent_type", sa.String(length=50), nullable=False),
        sa.Column("state_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"], ["experiments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_runs_experiment_id"),
        "agent_runs",
        ["experiment_id"],
        unique=False,
    )

    op.create_table(
        "attack_mutations",
        sa.Column("attack_id", sa.Uuid(), nullable=False),
        sa.Column("mutation_type", sa.String(length=100), nullable=False),
        sa.Column("mutated_prompt", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["attack_id"], ["attacks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attack_mutations_attack_id"),
        "attack_mutations",
        ["attack_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attack_mutations_attack_id"), table_name="attack_mutations")
    op.drop_table("attack_mutations")
    op.drop_index(op.f("ix_agent_runs_experiment_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index(op.f("ix_vulnerabilities_verified_status"), table_name="vulnerabilities")
    op.drop_index(op.f("ix_vulnerabilities_severity"), table_name="vulnerabilities")
    op.drop_index(
        op.f("ix_vulnerabilities_experiment_id"), table_name="vulnerabilities"
    )
    op.drop_index(op.f("ix_vulnerabilities_category"), table_name="vulnerabilities")
    op.drop_index(op.f("ix_vulnerabilities_attack_id"), table_name="vulnerabilities")
    op.drop_table("vulnerabilities")
    op.drop_index(op.f("ix_attack_results_attack_id"), table_name="attack_results")
    op.drop_table("attack_results")
    op.drop_index(op.f("ix_attacks_experiment_id"), table_name="attacks")
    op.drop_index(op.f("ix_attacks_category"), table_name="attacks")
    op.drop_table("attacks")
    op.drop_index(op.f("ix_experiments_project_id"), table_name="experiments")
    op.drop_index(op.f("ix_experiments_status"), table_name="experiments")
    op.drop_table("experiments")
    op.drop_index(op.f("ix_targets_project_id"), table_name="targets")
    op.drop_table("targets")
    op.drop_index(op.f("ix_projects_owner_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###